spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:realnestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.realnest: INFO
    org.springframework.security: WARN
